image: vichpetr/node-java-maven

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
- cd /builds/CDCP_TelcoDevel/snackbar/SnackBar/SnackBar && npm install

build:
  stage: build
  script:
  - cd /builds/CDCP_TelcoDevel/snackbar/SnackBar/SnackBar && npm run ng build --prod
  - cd /builds/CDCP_TelcoDevel/snackbar/backend && mvn package
  artifacts:
    paths:
    - /builds/CDCP_TelcoDevel/snackbar/SnackBar/SnackBar/dist/SnackBar
    - /builds/CDCP_TelcoDevel/snackbar/backend/target/backend-*.jar
