image: vichpetr/node-java-maven

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
- cd SnackBar/SnackBar && npm install

build:
  stage: build
  script:
  - cd SnackBar/SnackBar && npm run ng build --prod
  artifacts:
    paths:
    - SnackBar/SnackBar/dist/SnackBar
