spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/snackbar'
    username: snackbar
    password: snackpass
    driver-class-name: org.mariadb.jdbc.Driver
    banner:
      location: banner.txt
    jpa:
      #show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          #org.hibernate.dialect.MySQL5InnoDBDialect
          #ddl-auto: create-drop
          show_sql: true
          use_sql_comments: true
          format_sql: true
      generate-ddl: true
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl